feat: Add dockerfile for elixir-api, add favicons

diff --git a/elixir-api/bin/release b/elixir-api/bin/release
--- a/elixir-api/bin/release
+++ b/elixir-api/bin/release
@@ -1,36 +1,55 @@
-#!/usr/bin/env bash
+#!/bin/bash
 
 set -e
+MIX_ENV="prod"
 
-export MIX_ENV=$1
+while getopts ":p:d:t:a:" opt; do
+  case $opt in
+    p) SANITY_PROJECT_ID="$OPTARG"
+    ;;
+    d) SANITY_DATASET="$OPTARG"
+    ;;
+    t) SANITY_TOKEN="$OPTARG"
+    ;;
+    a) API_TOKEN="$OPTARG"
+    ;;
+    \?) echo "Invalid option -$OPTARG" >&2
+    ;;
+  esac
+done
 
-echo "Starting release build for $MIX_ENV...\r"
-cd /opt/build
+printf "Starting release build for $MIX_ENV...\r"
+cd /app
 
-source ./.env
-export SANITY_PROJECT_ID
-export SANITY_TOKEN
-export API_TOKEN
+if [ "$SANITY_DATASET" = "dev" ]; then
+  PORT=4444
+else
+  PORT=4000
+fi
+
 sed -i "s/\${SANITY_PROJECT_ID}/\"$SANITY_PROJECT_ID\"/g" ./config/$MIX_ENV.env.exs
 sed -i "s/\${SANITY_TOKEN}/\"$SANITY_TOKEN\"/g" ./config/$MIX_ENV.env.exs
+sed -i "s/\${SANITY_DATASET}/\"$SANITY_DATASET\"/g" ./config/$MIX_ENV.env.exs
 sed -i "s/\${API_TOKEN}/\"$API_TOKEN\"/g" ./config/$MIX_ENV.env.exs
+sed -i "s/\${PORT}/$PORT/g" ./config/$MIX_ENV.env.exs
 
-echo "Installing rebar3 and hex...\r"
-mix local.rebar --force
-mix local.hex --if-missing --force
+printf "Fetching project deps...\r"
+mix local.rebar --if-missing --force > /dev/null
+mix local.hex --if-missing --force > /dev/null
+mix deps.get --only $MIX_ENV > /dev/null
 
-echo "Fetching project deps...\r"
-mix deps.get --only prod
-
-echo "Cleaning any leftover build artifacts...\r"
+printf "Cleaning any leftover build artifacts...\r"
 mix do clean, compile --force
 
-echo "Building release for $MIX_ENV...\r"
-mix release $1 --overwrite
+printf "Building release for $MIX_ENV...\r"
+export MIX_ENV=$MIX_ENV
+mix release prod --overwrite
 
-echo "Release built successfully!\r"
 sed -i "s/\"$SANITY_PROJECT_ID\"/\${SANITY_PROJECT_ID}/g" ./config/$MIX_ENV.env.exs
 sed -i "s/\"$SANITY_TOKEN\"/\${SANITY_TOKEN}/g" ./config/$MIX_ENV.env.exs
+sed -i "s/\"$SANITY_DATASET\"/\${SANITY_DATASET}/g" ./config/$MIX_ENV.env.exs
 sed -i "s/\"$API_TOKEN\"/\${API_TOKEN}/g" ./config/$MIX_ENV.env.exs
+sed -i "s/$PORT/\${PORT}/g" ./config/$MIX_ENV.env.exs
+printf "Release built successfully!\r"
 
 exit 0
diff --git a/elixir-api/bin/start b/elixir-api/bin/start
--- a/elixir-api/bin/start
+++ b/elixir-api/bin/start
@@ -1,22 +1,18 @@
-#!/bin/sh
+#!/bin/bash
 
+set -e
 MODE="prod"
 optstring=":m:"
 
 while getopts ${optstring} arg; do
   case ${arg} in
     m)
-      # check for valid mode after -m
       if [ "$OPTARG" = "dev" ] || [ "$OPTARG" = "prod" ]; then
         MODE=$OPTARG
       else
-        echo "ERR: Invalid mode: $OPTARG"
+        echo "ERR: Invalid mode: '$OPTARG'"
         exit 1
       fi
-      ;;
-    :)
-      echo "ERR: Must supply an argument to -$OPTARG."
-      exit 1
       ;;
     ?)
       echo "ERR: Invalid option: -${OPTARG}."
@@ -26,26 +22,22 @@ while getopts ${optstring} arg; do
 done
 
 printf "Starting in $MODE mode...\r"
-
-# Check if CWD path 'scripts' directory, if so, change to parent directory
-if [ "${PWD##*/}" = "scripts" ]; then
+if [ "${PWD##*/}" = "bin" ]; then
   cd ..
 fi
 
-sleep 1
+if [ "$MODE" = "dev" ]; then
+  printf "Building dependencies...\r"
+  mix local.hex --if-missing --force > /dev/null
+  mix local.rebar --if-missing --force > /dev/null
+  mix deps.get > /dev/null
 
-printf "Installing Hex & rebar3...\r"
-mix local.hex --force > /dev/null 2>&1
-mix local.rebar --force > /dev/null 2>&1
+  printf "\r"
+  source ./.env
+  MIX_ENV=$MODE mix run --no-halt
+else
+  bin="/app/hexerei"
+  exec "$bin/prod/rel/prod/bin/prod" "start"
+fi
 
-# Install deps / install, hide output
-printf "Building dependencies...\r"
-mix deps.get > /dev/null 2>&1
-
-# Sleep for 1 second to fix some weird behavior I can't be arsed to debug rn
-sleep 1
-
-# Start server w/ mix
-printf "\r"
-source ./.env
-MIX_ENV=$MODE mix run --no-halt
+exit 0
