feat: Remove express-api dir and old references

diff --git a/elixir-api/bin/release b/elixir-api/bin/release
--- a/elixir-api/bin/release
+++ b/elixir-api/bin/release
@@ -3,7 +3,7 @@
 set -e
 MIX_ENV="prod"
 
-while getopts ":p:d:t:a:" opt; do
+while getopts ":p:d:t:a:x:" opt; do
   case $opt in
     p) SANITY_PROJECT_ID="$OPTARG"
     ;;
@@ -13,43 +13,44 @@ while getopts ":p:d:t:a:" opt; do
     ;;
     a) API_TOKEN="$OPTARG"
     ;;
+    x) PORT="$OPTARG"
+    ;;
     \?) echo "Invalid option -$OPTARG" >&2
     ;;
   esac
 done
 
-printf "Starting release build for $MIX_ENV...\r"
-cd /app
-
-if [ "$SANITY_DATASET" = "dev" ]; then
-  PORT=4444
-else
-  PORT=4000
+if [ -z "$SANITY_PROJECT_ID" ] || [ -z "$SANITY_DATASET" ] || [ -z "$SANITY_TOKEN" ] || [ -z "$API_TOKEN" ] || [ -z "$PORT" ]; then
+  echo "ERROR: Missing arguments for release"
+  exit 1
 fi
 
-sed -i "s/\${SANITY_PROJECT_ID}/\"$SANITY_PROJECT_ID\"/g" ./config/$MIX_ENV.env.exs
-sed -i "s/\${SANITY_TOKEN}/\"$SANITY_TOKEN\"/g" ./config/$MIX_ENV.env.exs
-sed -i "s/\${SANITY_DATASET}/\"$SANITY_DATASET\"/g" ./config/$MIX_ENV.env.exs
-sed -i "s/\${API_TOKEN}/\"$API_TOKEN\"/g" ./config/$MIX_ENV.env.exs
-sed -i "s/\${PORT}/$PORT/g" ./config/$MIX_ENV.env.exs
+printf "Starting release build for $SANITY_DATASET...\r"
+cd /app
+
+sed -i "s/\${SANITY_PROJECT_ID}/\"$SANITY_PROJECT_ID\"/g" ./config/prod.env.exs
+sed -i "s/\${SANITY_TOKEN}/\"$SANITY_TOKEN\"/g" ./config/prod.env.exs
+sed -i "s/\${SANITY_DATASET}/\"$SANITY_DATASET\"/g" ./config/prod.env.exs
+sed -i "s/\${API_TOKEN}/\"$API_TOKEN\"/g" ./config/prod.env.exs
+sed -i "s/\${PORT}/$PORT/g" ./config/prod.env.exs
 
 printf "Fetching project deps...\r"
 mix local.rebar --if-missing --force > /dev/null
 mix local.hex --if-missing --force > /dev/null
-mix deps.get --only $MIX_ENV > /dev/null
+mix deps.get --only prod > /dev/null
 
 printf "Cleaning any leftover build artifacts...\r"
 mix do clean, compile --force
 
-printf "Building release for $MIX_ENV...\r"
-export MIX_ENV=$MIX_ENV
+printf "Building release for $SANITY_DATASET...\r"
+export MIX_ENV=prod
 mix release prod --overwrite
 
-sed -i "s/\"$SANITY_PROJECT_ID\"/\${SANITY_PROJECT_ID}/g" ./config/$MIX_ENV.env.exs
-sed -i "s/\"$SANITY_TOKEN\"/\${SANITY_TOKEN}/g" ./config/$MIX_ENV.env.exs
-sed -i "s/\"$SANITY_DATASET\"/\${SANITY_DATASET}/g" ./config/$MIX_ENV.env.exs
-sed -i "s/\"$API_TOKEN\"/\${API_TOKEN}/g" ./config/$MIX_ENV.env.exs
-sed -i "s/$PORT/\${PORT}/g" ./config/$MIX_ENV.env.exs
+sed -i "s/\"$SANITY_PROJECT_ID\"/\${SANITY_PROJECT_ID}/g" ./config/prod.env.exs
+sed -i "s/\"$SANITY_TOKEN\"/\${SANITY_TOKEN}/g" ./config/prod.env.exs
+sed -i "s/\"$SANITY_DATASET\"/\${SANITY_DATASET}/g" ./config/prod.env.exs
+sed -i "s/\"$API_TOKEN\"/\${API_TOKEN}/g" ./config/prod.env.exs
+sed -i "s/$PORT/\${PORT}/g" ./config/prod.env.exs
 printf "Release built successfully!\r"
 
 exit 0
